services:
  db:
    image: postgres:15-alpine
    container_name: riot-tracker-db
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: riot_user
      POSTGRES_PASSWORD: riot_pass_2024
      POSTGRES_DB: riot_tracker





